// Generated by Wrangler on Tue Jul 30 2024 10:00:00 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
  DB: D1Database;
  ASSETS: Fetcher;
  NODE_ENV: "development" | "production" | "test";
  VITE_PORT: string;
}
